clean:
	gnatclean task1 task3 task4 task5
	rm -f *.ali *.o *.sli *.lst spark.rep code.sum
	rm -rf task1/
	rm -rf task3/
	rm -rf task4/
	rm -rf task5/
	rm -rf task3solution/
	rm -rf task4solution/
	rm -rf task4solution/

CLEAN: clean
